import 'bootstrap/dist/css/bootstrap.min.css'
import '@app/styles/globals.css'
import {QueryClient, QueryClientProvider} from "react-query";
import Head from "next/head";
import styles from "@app/styles/Home.module.css";
import Link from "next/link";
import {Card, Col, Container, FormControl, Row} from "react-bootstrap";

const queryClient = new QueryClient()

const MyApp = ({Component, pageProps}) =>
    <QueryClientProvider client={queryClient}>
        <Head>
            <title>Cars</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className={styles.main}>
            <nav>

              <Link href="/login"> HOME </Link>
              <Link href="/">| SSR </Link>
              <Link href="/ssg">| SSG </Link>
              <Link href="/mixed">| CSR-SSR </Link>
            
            </nav>
           
            <br/>
            <Component {...pageProps} />
        </main>



        <footer className={styles.footer}>
            
        </footer>
    </QueryClientProvider>
;

export default MyApp